# Site settings
title: AustinTechVideos.com
email: austintechvideos@llbbl.com
description: "Nerdin it up in Austin"
baseurl: ""
url: ""

# Pagination
# paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['node_modules', 'bower_components']

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"